POST http://localhost:3002/vehicles/getprice
Content-Type: application/json

{
      "id": 3,
      "brand": "BMW",
      "model": "Z4",
      "category": "C",
      "price": 60,
      "createdAt": null,
      "updatedAt": null
    },

###

GET http://localhost:3002/vehicles/
# Content-Type: application/json

# {
#     "category":"A"
# }